### ISSUE TITLE
Preparar uma interface para exibição dos relatos de experiências ao ser selecionado para visualização 

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#106]
Benchmarking: https://apsredes.org/aps-forte-no-sus/conviver-mais-atividade-fisica-atraves-da-intersetorialidade-para-municipes-do-jaboatao-dosguararapes/

Relatos publicados: https://mtci.teste.bvsalud.org/relatos/
https://sms.sp-new.teste.bvs.br/relatos
https://bestpractices.teste.bvsalud.org/best-practices/

Lembrando que a interface de resultado dos relatos se manterá, deverá ser criada uma interface para a exibição de cada relato individualmente.

**Comment by wilsonmoura** [comment]
Relacionado com bireme/relatos-wp-plugin#16

**Comment by marcioalvessilva** [comment]
Etapa concluída, aguardo feedback.
Um issue complementar para inserir LightBox nas Imagens foi aberto - https://github.com/bireme/relatos-wp-plugin/issues/17

Teste - https://sms.sp-new.teste.bvs.br/relatos

**Comment by wilsonmoura** [comment]
Ajustes realizados em bireme/relatos-wp-plugin#16
