### ISSUE TITLE
Na aba equipe > membros > novo membro > não está permitindo incluir mais de um membro aparece a mensagem de que já existe

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#108]
A consultora identificou o mesmo problema no campo responsável. Eu testei e funcionou

**Comment by wilsonmoura** [comment]
@barrosjo realizamos testes e funcionou corretamente. Vale destacar que o sistema não permite membros com o mesmo e-mail. Essa regra também se aplica ao adicionar responsáveis.

**Comment by barrosjo** [comment]
Na produção voltou a dar o problema "Membro já existe" e não deixar salvar novos membros: https://experiencias.bvsalud.org/submission/new/106/fourth

**Comment by wilsonmoura** [comment]
@barrosjo provavelmente deve ser algum campo que passou o limite máximo de caracteres. Para que possamos simular, favor compartilhar os dados do membro que gerou o erro mencionado.

**Comment by wilsonmoura** [comment]
@barrosjo ajustes realizados. Favor validar.
