### ISSUE TITLE
Ajustar a interface de apresentação de um relato completo seguindo a estrutura a seguir

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#114]
Laranja (14 ao 19): Detalhes da Experiência
Verde (20 e 21): Equipe
Amarelo (22* ao 25): Arquivos
Rosa e Azul (1 ao 13, 26 ao 29): Outras informações

*no campo 22 (Texto completo e documento) tentar deixar junto, cada um com um ícone: um para abrir e ler na própria página e outra para baixar o pdf, por exemplo. 
![20221216_112145](https://user-images.githubusercontent.com/19578003/208121457-32a8bcab-43b8-414c-88df-778da243d2d0.jpg)
![20221216_112152](https://user-images.githubusercontent.com/19578003/208121470-e1a42d1c-8af6-43bd-b010-8e6a841fa40c.jpg)
![20221216_112204](https://user-images.githubusercontent.com/19578003/208121471-f6912488-c53c-4b29-b89c-b1d3b4fe85e8.jpg)

**Comment by barrosjo** [comment]
@wilsonmoura essa isue é pra ajuste da interface pública (ex.: https://sms.sp-new.teste.bvs.br/relatos/resource/?id=52) seguindo essa mesma estrutura de apresentação do dados, por isso foi incluído o @marcioalvessilva

**Comment by wilsonmoura** [comment]
@barrosjo os issues para ajustes na interface pública devem ser registrados em outro projeto no GitHub: [relatos-wp-plugin](https://github.com/bireme/relatos-wp-plugin)

Sendo assim, criei um issue nesse projeto para documentar as atividades dessa demanda: bireme/relatos-wp-plugin#18

**Comment by wilsonmoura** [comment]
Ajustes realizados pelo @marcioalvessilva em bireme/relatos-wp-plugin#18

**Comment by wilsonmoura** [comment]
@barrosjo ajustes realizados pelo @marcioalvessilva em bireme/relatos-wp-plugin#18. Favor validar.
