### ISSUE TITLE
Ajustes na página de apresentação dos relatos

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#120]
Lista de ajustes:
- Não exibir o nome "Detalhes da Experiência"
- Incluir quebra de linha nos textos

**Comment by wilsonmoura** [comment]
Ajustes realizados em bireme/relatos-wp-plugin#25

**Comment by barrosjo** [comment]
A quebra de linha não está sendo exibida no campo "Texto Completo"

**Comment by wilsonmoura** [comment]
@barrosjo ajustes realizados.
