### ISSUE TITLE
Ajustar o espaçamento entre os títulos do menu para não sobrepor o título abaixo

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#121]
![Relatos de Experiências   Relatos de Experiências (1)](https://user-images.githubusercontent.com/19578003/234067667-c5de0479-e696-4aea-8269-247c1a9c80ac.png)

**Comment by marcioalvessilva** [comment]
Inserir CSS

@media (max-width: 1300px){
	.nav>li>a{
	padding:10px 5px;
	}
}
@media (max-width: 1024px){
	.nav>li>a{
	padding:10px 5px;
	font-size:11px;
	}
}
