### ISSUE TITLE
Erro ao tentar carregar um vídeo no registro de um relato

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#122]
![An Error Occurred  Not Found (1)](https://user-images.githubusercontent.com/19578003/234086035-d2f24023-b5b2-407b-a5aa-3b0c5b0931d4.png)

**Comment by wilsonmoura** [comment]
@barrosjo ajustes realizados. Favor validar.

**Comment by barrosjo** [comment]
Funcionando.
