### ISSUE TITLE
No ambiente de produção está dando erro ao gerar o pdf de uma experiência registrada e por isso não é possível submeter uma nova experiência

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#123]
Problemas ao gerar o PDF. Por favor, contate o administrador.

**Comment by wilsonmoura** [comment]
@barrosjo identificamos que a biblioteca que gera os arquivos PDF não estava corretamente instalada e configurada no ambiente de produção. Favor validar.
