### ISSUE TITLE
Parece que há uma sicronização automática (em tempo real) dos relatos do ambiente de teste com o ambiente de produção e vice versa

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#124]
Dois testes:
-Ontem foram enviados 3 relatos da sms no ambiente de teste e já estão na produção com o mesmo status.
-Hoje subi um relato na coleção sms como teste no ambiente de produção e o mesmo também já se encontra nos relatos no ambiente de teste

**Comment by wilsonmoura** [comment]
@barrosjo nós ajustamos o ambiente de testes para atualizar somente o índice de pesquisa do ambiente de testes. Também atualizamos o índice do ambiente de produção para remover os relatos do ambiente de testes que foram publicados por engano. Favor validar.
