### ISSUE TITLE
Não está funcionando a opção "Esqueci minha senha"

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#125]
O e-mail é enviado apenas com o número 6 no corpo do texto
![image](https://github.com/bireme/relatos-experiencia/assets/19578003/930a6086-8f03-4e91-bb63-8d4a6bba332c)

**Comment by wilsonmoura** [comment]
@barrosjo por padrão, em alguns casos, as mensagens de e-mail só estão traduzidas no idioma inglês. Favor acessar o menu `Administração do Sistema >> Mensagens do Correio` e incluir as devidas traduções.
