### ISSUE TITLE
Ao editar um relato já aprovado, o sistema salva automaticamente as alterações mesmo excluindo informação de campo obrigatório.

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#132]

**Comment by wilsonmoura** [comment]
@barrosjo fizemos alguns testes e não conseguimos reproduzir esse erro. Poderia dar mais detalhes?

**Comment by wilsonmoura** [comment]
@barrosjo vamos encerrar esse issue e reabrir caso necessário.
