### ISSUE TITLE
Na interface pública, ao lado do país, mostra um quadrado em branco, seria para aparecer a bandeira?

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#133]

**Comment by wilsonmoura** [comment]
@acecampos provavelmente o plugin está desatualizado. Favor solicitar via OCOMON a atualização do plugin no respectivo site. Após isso, confirmar se problema foi ou não resolvido.

**Comment by acecampos** [comment]
@wilsonmoura, acho que seria para @barrosjo :)

**Comment by barrosjo** [comment]
ok. Aguardando atendimento do chamado no ocomon.
