### ISSUE TITLE
No menu da plataforma há uma marcação fixa no ítem "Nova Submissão", mesmo estando em outra aba o item "Nova Submissão" continua marcado

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#136]
![image](https://github.com/bireme/relatos-experiencia/assets/19578003/2229bc4a-d5e7-4549-a12f-c846ba602e64)

**Comment by wilsonmoura** [comment]
@acecampos o ítem "Nova Submissão" na verdade é um botão. Para que não haja confusão, podemos manter o mesmo padrão apresentado no menu principal. Favor confirmar para que possamos prosseguir ou, se for o caso, ou apresentar outra sugestão.

**Comment by wilsonmoura** [comment]
@acecampos o ítem "Nova Submissão" na verdade é um botão. Para que não haja confusão, podemos manter o mesmo padrão apresentado no menu principal. Favor confirmar para que possamos prosseguir ou, se for o caso, apresentar outra sugestão.

**Comment by acecampos** [comment]
@wilsonmoura, acho que é para a @barrosjo... :)

**Comment by barrosjo** [comment]
@wilsonmoura neste caso melhor manter o padrão do menu principal. De toda forma seria importante conseguir identificar em qual aba do menu o usuário da plataforma está
