### ISSUE TITLE
No campo População manter lista controlada e ao selecionar a opção "outro" abrir um novo campo para ser incluído manualmente

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#21]
Essa informação incluída manualmente deverá passar por validação

**Comment by barrosjo** [comment]
O campo "Outra população" continua aparecendo aberta por default

**Comment by wilsonmoura** [comment]
@barrosjo ajustes realizados.

**Comment by barrosjo** [comment]
@wilsonmoura identifiquei que o campo "Outras populações" só é aberto caso a opção "Outros" seja selecionado sozinho no campo "População". Caso seja selecionado junto com outra opção, o campo não abre.
