### ISSUE TITLE
Na aba usuário, erro ao tentar "Obter o link de usuário para alterar a senha" no símbolo do cadeado

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#26]
![An_Error_Occurred_Not_Found_-_2022-05-31_10 26 07](https://user-images.githubusercontent.com/19578003/171184266-6fef363a-9b9a-45fd-adef-9967bf45d59d.png)

**Comment by wilsonmoura** [comment]
@barrosjo tentamos simular o erro, mas sem sucesso. Favor testar novamente e confirmar se o erro ainda persiste.

**Comment by wilsonmoura** [comment]
@barrosjo vamos encerrar esse issue e reabrir caso o problema ocorra novamente.
