### ISSUE TITLE
Manter somente 3 perfis de usuário

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#29]
Documentalista: registra a experiência
Editor: que valida e publica
Administrador: gere o sistema, cria usuário, etc.

**Comment by wilsonmoura** [comment]
@barrosjo de acordo com a solicitação, teremos então que desativar 2 perfis de usuário:

- Membro ad hoc
- Membro do comitê

Vale reforçar que, após a submissão do relato pelo documentalista, o processo de aprovação passa por 3 etapas:

- Analisar
- Avaliação inicial do comitê
- Finalizar revisão

Com esse ajuste nos perfis de usuário, a etapa **Avaliação inicial do comitê** não será mais necessária, pois essa etapa serve apenas para convidar os membros adhoc ou membros do comitê para avaliarem os relatos. Sendo assim, favor confirmar se devemos manter essa etapa (não obrigatória) ou se mantemos o fluxo de aprovação no formato original.

**Comment by wilsonmoura** [comment]
@barrosjo de acordo com a solicitação, teremos então que desativar 2 perfis de usuário:

- Membro ad hoc
- Membro do comitê

Vale reforçar que, após a submissão do relato pelo documentalista, o processo de aprovação passa por 3 etapas:

- Analisar
- Avaliação inicial do comitê
- Finalizar revisão

Com esse ajuste nos perfis de usuário, a etapa **Avaliação inicial do comitê** não será mais necessária, pois essa etapa serve apenas para convidar os membros adhoc ou membros do comitê para avaliarem os relatos. Sendo assim, favor confirmar se devemos ou não manter essa etapa (não obrigatória).

**Comment by wilsonmoura** [comment]
@barrosjo de acordo com a solicitação, teremos então que desativar 2 perfis de usuário:

- Membro ad hoc
- Membro do comitê

Vale reforçar que, após a submissão do relato pelo documentalista, o processo de aprovação passa por 3 etapas:

- Analisar
- Avaliação inicial do comitê (opcional)
- Finalizar revisão

Com esse ajuste nos perfis de usuário, a etapa **Avaliação inicial do comitê** não será mais necessária, pois essa etapa serve apenas para convidar os membros adhoc ou membros do comitê para avaliarem os relatos. Sendo assim, favor confirmar se devemos ou não manter essa etapa.

**Comment by wilsonmoura** [comment]
@barrosjo de acordo com a solicitação, teremos então que desativar 2 perfis de usuário:

- Membro ad hoc
- Membro do comitê

Vale reforçar que, após a submissão do relato pelo documentalista, o processo de aprovação passa por 3 etapas:

- Analisar
- Avaliação inicial do comitê (opcional)
- Finalizar revisão

Com esse ajuste nos perfis de usuário, a etapa **Avaliação inicial do comitê** não será mais necessária, pois essa etapa serve apenas para convidar os membros adhoc ou membros do comitê para avaliarem os relatos. Sendo assim, favor confirmar se devemos ou não manter essa etapa no fluxo de aprovação dos relatos.

**Comment by barrosjo** [comment]
@wilsonmoura de acordo. Pode desativar os 2 perfis de usuário:

Membro ad hoc
Membro do comitê

No caso dos perfis Investigator e Secretary, alterar os nomes para Documentalista e Editor, respectivamente.
