### ISSUE TITLE
Perguntas frequentes: apagar o conteúdo atual e ocultar o campo do menu até que novos conteúdos sejam desenvolvidos

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#34]
https://experiencias.teste.bvsalud.org/public/faq

**Comment by wilsonmoura** [comment]
@barrosjo o submenu **Perguntas frequentes** foi movido para o menu **Administração**. Os conteúdos podem ser apagados usando uma conta com o perfil de **Administrador**.

Ajustes realizados em #37

**Comment by barrosjo** [comment]
Ok! Excluí as perguntas referentes ao ProEthos
