### ISSUE TITLE
Excluir do menu o item comitê e os itens subordinados pois o conteúdo já aparece no menu

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#37]
![image](https://user-images.githubusercontent.com/19578003/171729102-d3dd4575-043a-4ec0-93e1-13cd1fcfabd5.png)

**Comment by wilsonmoura** [comment]
Ajustar o menu da seguinte forma:
- Mover os submenus Perguntas Frequentes e Ajuda para o menu Administração do Sistema
- Mudar o nome do menu Experiências para Minhas Experiências
- Mudar o nome do menu Comitê para Experiências
- Em Painel de Controle, exibir seção com os relatos que foram avaliados pelo editor

**Comment by wilsonmoura** [comment]
Ajustar o menu da seguinte forma:
- Mover os submenus Perguntas Frequentes e Ajuda para o menu Administração do Sistema
- Mudar o nome do menu Experiências para Minhas Experiências
- Mudar o nome do menu Comitê para Experiências
- Em Painel de Controle, exibir seção com a lista de relatos que foram avaliados pelo editor

**Comment by wilsonmoura** [comment]
Ajustar o menu da seguinte forma:
- Mover os submenus Perguntas Frequentes e Ajuda para o menu Administração do Sistema
- Mudar o nome do menu Experiências para Minhas Experiências
- Mudar o nome do menu Comitê para Experiências
