### ISSUE TITLE
No status do Relato excluir a opção "Programado" e manter somente: Rascunho, Enviado, Aprovado e Não Aprovado

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#43]

**Comment by wilsonmoura** [comment]
@barrosjo o status **Programado** serve pra informar que a submissão do relato feito pelo documentalista está na fase final do fluxo de aprovação (aba **Finalizar revisão**). Creio que, nesse caso, o ideal seria modificar esse texto para algo que seja mais claro para o usuário.

**Comment by barrosjo** [comment]
Isso faz sentido pro ProEthos, no caso dos Relatos de Experiência não teremos essa fase de finalizar revisão. Acredito que essa aba pode sair pois nem consegui acessá-la.

**Comment by wilsonmoura** [comment]
@barrosjo o sistema não permite a remoção das etapas **Analisar** e **Finalizar revisão**, pois ambas são obrigatórias dentro desse fluxo de aprovação. Se for o caso, podemos alterar alguns rótulos ou campos para chegar próximo daquilo que seria ideal dentro do contexto de relatos de experiência.

**Comment by wilsonmoura** [comment]
Conforme definido em reunião com a equipe, vamos refazer a camada do fluxo de aprovação para atender as necessidades dentro do contexto de relatos de experiência.
