### ISSUE TITLE
Manter o ícone do lápis somente para edição, para avaliação substituir por outro ícone

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#48]

**Comment by wilsonmoura** [comment]
@barrosjo favor sugerir um novo ícone para substituição. A lista de ícones está disponível no link abaixo:

https://www.w3schools.com/bootstrap/bootstrap_ref_comp_glyphs.asp

**Comment by barrosjo** [comment]
@wilsonmoura acredito que possa tentar esse: glyphicon glyphicon-ok e vemos como fica
