### ISSUE TITLE
Não foi possível apagar os itens inativos da lista controlada: "Áreas temáticas" mesmo com o perfil de administrador

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#49]

**Comment by wilsonmoura** [comment]
@barrosjo por questões de integridade de dados, os itens das listas controladas não podem ser removidos, mas podem ser desativados.

Vale reforçar que essa lista foi criada como exemplo para ser usada nos testes inicias do sistema. Se for o caso, podemos zerar essa lista para que possam incluir os itens desejados.
