### ISSUE TITLE
A lista controlada "Grupos Populacionais" está em inglês

### ISSUE THREAD

**Issue by barrosjo** [bireme/relatos-experiencia#50]

**Comment by wilsonmoura** [comment]
@barrosjo a lista controlada Grupos Populacionais pode ser editada e traduzida no menu `Administração do Sistema >> Listas Controladas >> Grupos Populacionais`

**Comment by wilsonmoura** [comment]
@barrosjo a lista controlada Grupos Populacionais pode ser editada e traduzida no menu `Administração do Sistema >> Listas Controladas >> Grupos Populacionais`.

Vale reforçar que essa lista foi criada como exemplo para ser usada nos testes inicias do sistema. Se for o caso, podemos zerar essa lista para que possam incluir os itens desejados.

**Comment by barrosjo** [comment]
@wilsonmoura lista traduzida no local indicado. Não identifiquei onde ordenar a lista em ordem alfabética. 

Vou validar os termos incluídos, mas acredito que podemos manter dessa forma e ir adicionando termos novos.

**Comment by barrosjo** [comment]
@wilsonmoura na administração do sistema a lista controlada aparece em ordem alfabética, porém, ao cadastrar um novo relato a lista é exibida em ordem aleatória

**Comment by wilsonmoura** [comment]
@barrosjo ajustes realizados.
